services:
   api:
    build:
      context: "."
      dockerfile: Dockerfile
    container_name: "api"
    ports:
      - "5000:8080"
      - "5001:8081"
    networks:
      - app-network
      
networks:
   app-network:
       driver: bridge

  # webapp:
  #   image: webapp:dev
  #   container_name: webapp_compose
  #   restart: unless-stopped
  #   build:
  #     context: "../"
  #     dockerfile: Dockerfile
  #   ports:
  #     - "9000:8080"
  #     - "9001:8081"
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - ASPNETCORE_HTTP_PORTS=8080 
